### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#188]
Some code review ideas:

For backend:
- why it's not recommend to use component and scope in the entity files
- why it's not recommend to use inject (built in autowired annotation)
- not use public class attributes, for vo, could rename to dto if just want to use as data record

**Comment by paulushcgcj** [comment]
### why it's not recommended to use component and scope in the entity files

Entity classes are supposed to be session-bounded. By annotating a class with `@Component` you're flagging it for spring to instantiate it as a managed bean, keeping it as a singleton.

As an entity is supposed to be just a data holder for the database, it makes no sense to use it as a component.

The scope controls the component scope or in simple words, marks how spring will control this singleton lifecycle. You can set a scope per user session (meaning that a bean will exist for each user session) or more global.

**Comment by paulushcgcj** [comment]
### why it's not recommend to use inject (built in autowired annotation)

As mentioned, spring already contains its own DI annotation `@Autowired`. Spring already manages it internally with `@Autowired` so it is not required to add another dependency for this.

**Comment by paulushcgcj** [comment]
### not use public class attributes, for vo, could rename to dto if just want to use as data record

Java is pretty strict on its naming convention and lots of libs make use of reflection to access some classes. By setting a class property as public, you're violating some of its conventions and things such as hibernate could end up failing due to that.

Also, another naming convention as mentioned is DTO (Data Transfer Object) when we are dealing with objects that are used only for sending and receiving data. As suggested, we can make use of Java 14 feature called `record` to have smaller and simpler objects that hold data for transfer.

**Comment by MCatherine1994** [comment]
Thanks @paulushcgcj!!
