### ISSUE TITLE
FSADT1-305: Copy data from Oracle view to a local DB

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#19]
[FSADT1-305](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-305) Copy data from Oracle view to a local DB

**Comment by mamartinezmejia** [comment]
This task was created to have an option in case the final user needs to query all data at once and have a better performance.

Option #1: Copy data to a local DB using NestJS, OpenShift and Postgres.
We tried this but there were some challenges:
1.	If we query the whole data, JavaScript will get the browser frozen or the computer out of memory.
2.	If we compare the existing records with the ones in the Oracle DB, we get the following error because we must do this within a loop:

Error: connect ECONNREFUSED

Note: This error doesn’t happen if we do it outside of a loop.

Option #2: Copy data with other options.
-	Oracle Procedure: This task must be done by a DBA. We will need to provide access to our local DB. 
The problem with this solution is that we don’t have any control over this procedure, so we cannot know if it works properly.

-	FME: This solution seems to be a good one, specially that other teams have used it. The problem with this one is that it doesn’t work with OpenShift and it will be a learning curve for developers.
