### ISSUE TITLE
Potential: roll PR commenter into PR description editor

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-forest-client#234]
PR commenting creates more updates and emails than adding to PR descriptions.  Discuss and investigate.  If a yes, then it should be pretty trivial to pull off.

**Comment by paulushcgcj** [comment]
The **action-pr-description-add** commenter is generating some dups on the PR description. If you check #209 you will see more than one entry. Dunno if this was something that happened only this time or if this was observed in other teams as well.

My suggestion would be to keep the **thollander/actions-comment-pull-request** on its latest version, as it helps visualize the actual changelog. This also can be used to include comments or failures that happened during the process.

It can add some noise, but it serves the purpose of notifying users about what happened (for things such as deployment failed due to space/resource utilization restrictions).

Just an idea to spark some feedback from the actions to the users/developers

**Comment by DerekRoberts** [comment]
thollander/actions-comment-pull-request has created nine comments in https://github.com/bcgov/nr-forest-client/pull/228.  @paulushcgcj doesn't seem to mind, so this is getting closed!  We can always revisit later.
